roiManager("Select", 0);
run("Measure");
roiManager("Select", 1);
run("Measure");
roiManager("Select", 2);
run("Measure");
roiManager("Select", 3);
run("Measure");
roiManager("Select", 4);
run("Measure");
roiManager("Select", 5);
run("Measure");
roiManager("Select", 6);
run("Measure");
roiManager("Select", 7);
run("Measure");
roiManager("Select", 8);
run("Measure");
roiManager("Select", 9);
run("Measure");
roiManager("Select", 10);
run("Measure");
roiManager("Select", 11);
run("Measure");
roiManager("Select", 12);
run("Measure");
roiManager("Select", 13);
run("Measure");
roiManager("Select", 14);
run("Measure");
roiManager("Select", 15);
run("Measure");
roiManager("Select", 16);
run("Measure");
roiManager("Select", 17);
run("Measure");
roiManager("Select", 18);
run("Measure");
roiManager("Select", 19);
run("Measure");
roiManager("Show All");
