function [fitresult, gof] = createFits(RTK, XVI, RTK17, XVI17)
%CREATEFITS(RTK,XVI,RTK17,XVI17)
%  Create fits.
%
%  Data for 'Tomo' fit:
%      X Input : RTK
%      Y Output: XVI
%  Data for 'Scan17' fit:
%      X Input : RTK17
%      Y Output: XVI17
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Apr-2018 02:48:23

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Tomo'.
[xData, yData] = prepareCurveData( RTK, XVI );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Tomo' );
h = plot( fitresult{1}, xData, yData, 'predobs' );
legend( h, 'XVI vs. RTK', 'Tomo', 'Lower bounds (Tomo)', 'Upper bounds (Tomo)', 'Location', 'NorthEast' );
% Label axes
xlabel RTK
ylabel XVI
grid on

%% Fit: 'Scan17'.
[xData, yData] = prepareCurveData( RTK17, XVI17 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Scan17' );
h = plot( fitresult{2}, xData, yData, 'predobs' );
legend( h, 'XVI17 vs. RTK17', 'Scan17', 'Lower bounds (Scan17)', 'Upper bounds (Scan17)', 'Location', 'NorthEast' );
% Label axes
xlabel RTK17
ylabel XVI17
grid on

figure( 'Name', ' Both' );
h = plot( fitresult{1}, xData, yData, 'predobs' );
legend( h, 'XVI vs. RTK', 'Tomo', 'Lower bounds (Tomo)', 'Upper bounds (Tomo)', 'Location', 'NorthEast' );
hold on
h = plot( fitresult{2}, xData, yData, 'predobs' );
legend( h, 'XVI17 vs. RTK17', 'Scan17', 'Lower bounds (Scan17)', 'Upper bounds (Scan17)', 'Location', 'NorthEast' );


